# Generated by Django 5.0.2 on 2024-02-26 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='gestion.categoria'),
        ),
    ]
